### ISSUE TITLE
Right Click on Activity causes exception.

### ISSUE THREAD

**Issue by pointan** [delas/plg#10]
I wanted to add an activity time using the python script. As soon as I press right click on the activity an exception is thrown and thus does not open the context menu. This bug occurs for me both in java 8 and java 11 (the current versions can be seen in the screenshots below).

![grafik](https://user-images.githubusercontent.com/7925259/88926063-b81aeb80-d275-11ea-96fc-d61e95df344f.png)

![grafik](https://user-images.githubusercontent.com/7925259/88926127-ccf77f00-d275-11ea-8c13-dd2a6cfc43d2.png)

I was able to fix this bug locally for me by changing the load image behavior in the ImageUtils class of the libPlgVisualizer project. 

Therefore I changed the line: 
```java
return new ImageIcon(ImageIO.read(ClassLoader.getSystemResource(imageFile)));
```

to: 

```java
return new ImageIcon(ImageIO.read(ImageUtils.class.getResource(imageFile)));
```

**Comment by WeiWeic6222848** [comment]
I fixed this bug locally by changing the ImageCollection class, I deleted all the heading slashes from it.
![image](https://user-images.githubusercontent.com/22558527/99148953-294aa700-268b-11eb-873c-a20c94445793.png)
delete first '/' in all paths
