### ISSUE TITLE
exported log file is empty

### ISSUE THREAD

**Issue by alessandro-rizzo** [delas/plg#11]
Hi, I'm trying to generate a log from a process. I can see that the generation starts and a file is created but is empty (even though the progress bar has completed). Am I missing something or is this a bug?

![image](https://user-images.githubusercontent.com/43115234/99079364-c20ff280-25b7-11eb-85b1-0bc339f1c4da.png)

**Comment by mostapow** [comment]
I had the same issue, check if you're using Java 8 instead of Java 11

**Comment by WeiWeic6222848** [comment]
I had the same issue, I solved it by building jar files for each library individually, then use the jar file as dependency instead of the src folder.
I think it has somthing to do with OpenXES.jar and that it cannot find DataTypeConverter class.

**Comment by mgroeschel** [comment]
> 
> 
> I had the same issue, check if you're using Java 8 instead of Java 11

 I had the same problems. Running PLG with Java 8 fixed the problem! Thanks

**Comment by delas** [comment]
Closed in release https://github.com/delas/plg/releases/tag/2.1.0
