### ISSUE TITLE
Right-click button doesn't work

### ISSUE THREAD

**Issue by matheusPereiraAlmeida** [delas/plg#12]
I downloaded the v2.0.6 .jar file from the link https://plg.processmining.it/. And I'm able to generate a new process. However, when I press the right-click button, for some reason I don't see the menu displayed as in the demo video available in the web site. Does anyone know what can be happening?

![image](https://user-images.githubusercontent.com/61329801/151077306-9fe5eca5-5a39-42ae-bdf1-b4d46d97c0e8.png)

**Comment by delas** [comment]
- Which version of Java are you using (`java -version`)?
- Have you tried to run the program from the command line with `java -jar plg-2.0.6.jar` and see whether you get any exceptions?
- Also, have you tried with PLG 2.0.5?

**Comment by delas** [comment]
The new release v2.0.7 (https://github.com/delas/plg/releases/tag/2.0.7) should fix the bug (which was actually a duplicate of #10).
